/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'gym' : IDL.Null,
  'men' : IDL.Null,
  'watches' : IDL.Null,
  'other' : IDL.Null,
  'women' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'imageLink' : IDL.Text,
  'category' : Category,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  'filterProductsByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getProductById' : IDL.Func([IDL.Nat], [Product], ['query']),
  'listAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'gym' : IDL.Null,
    'men' : IDL.Null,
    'watches' : IDL.Null,
    'other' : IDL.Null,
    'women' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'imageLink' : IDL.Text,
    'category' : Category,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    'filterProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProductById' : IDL.Func([IDL.Nat], [Product], ['query']),
    'listAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };